markdown: kramdown
permalink: /:title.html
url: https://blog.billyz.top
lsi: true
highlighter: rouge
safe: true
auto: true

# presonal config
title: Just Do it
feed: 
comments: disqus

author:
  name: billy.zheng
  nickname: cnsystem
  gmail: billyzheng1990@gmail.com
  qqmail: 
  qqlist: 
  site: 

seo: 
  keyword: billyzheng,cnsystem
  description: blog

config:
  js_dir: 
  img_dir: images
  css_dir:
